# Generated by Django 5.2.5 on 2025-09-23 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelExpenseField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('label',)},
            },
        ),
        migrations.CreateModel(
            name='HotelExpenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('notes', models.CharField(blank=True, max_length=150, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='HotelApp.hotelexpensefield')),
            ],
        ),
    ]
