# Generated by Django 5.2.5 on 2025-09-20 17:29

import HotelApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Served', 'Served'), ('In Progress', 'In Progress')], db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=HotelApp.models.food_item_image_path),
        ),
    ]
