# Generated by Django 5.2.5 on 2025-09-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0003_hotelexpensefield_hotelexpenserecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='HotelOrderItem',
        ),
    ]
