# Generated by Django 5.2.5 on 2025-09-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0003_order_order_status_alter_fooditem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='description',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Served', 'Served'), ('In Progress', 'In Progress')], db_index=True, default='In progress'),
        ),
    ]
