# Generated by Django 5.2.5 on 2025-09-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0004_remove_fooditem_description_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Served', 'Served'), ('In Progress', 'In Progress')], db_index=True, default='In Progress'),
        ),
    ]
