"""
Django settings for LaundryConfig project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
import os
from LaundryConfig.env import BASE_DIR, env
import dj_database_url
from decouple import config

# import dj_database_url
# from decouple import config

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')
TWILIO_ACCOUNT_SID = env("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = env("TWILIO_AUTH_TOKEN")
TWILIO_PHONE_NUMBER = env("TWILIO_PHONE_NUMBER")




# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DJANGO_DEBUG', default=False)  # Set to False for production

# This allows your Render URL to be a valid host
ALLOWED_HOSTS = ['laundry12-4.onrender.com', '*']

SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False


# NPM_BIN_PATH = os.environ.get("NPM_BIN_PATH", None)
# Application definition

INSTALLED_APPS = [
    # IMPORTANT: Add whitenoise to INSTALLED_APPS for it to be recognized
    # by collectstatic and for its static file storage engine to work.
    'whitenoise.runserver_nostatic', # For development
    'multiselectfield', 
    "unfold",
    'django_registration',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'LaundryApp',
    'HotelApp',
    
    'tailwind',
    'crispy_forms',
    'import_export',
    'django_daraja',
    'theme',
    'compressor',
    "widget_tweaks",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Place Whitenoise middleware at the top for efficiency
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ACCOUNT_ACTIVATION_DAYS = 0  # One-week activation window
REGISTRATION_OPEN = True
TAILWIND_APP_NAME = 'theme'
TAILWIND_CONFIG_FILE = 'tailwind.config.js'
TAILWIND_CSS_INPUT_FILE = 'src/input.css'
TAILWIND_CSS_OUTPUT_FILE = 'css/output.css'

CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"



EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_AUTO_FIELD = env('DEFAULT_AUTO_FIELD')

MPESA_ENVIRONMENT = env('MPESA_ENVIRONMENT')
MPESA_CONSUMER_KEY = env('MPESA_CONSUMER_KEY')
MPESA_CONSUMER_SECRET = env('MPESA_CONSUMER_SECRET')
MPESA_SHORTCODE = env('MPESA_SHORTCODE')
MPESA_EXPRESS_SHORTCODE = env('MPESA_EXPRESS_SHORTCODE')
MPESA_SHORTCODE_TYPE = env('MPESA_SHORTCODE_TYPE')
MPESA_PASSKEY = env('MPESA_PASSKEY')
MPESA_INITIATOR_USERNAME = env('MPESA_INITIATOR_USERNAME')
MPESA_INITIATOR_SECURITY_CREDENTIAL = env('MPESA_INITIATOR_SECURITY_CREDENTIAL')

# For development: emails will be printed to the console


# For production: use real SMTP (example with Gmail)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')  # not your Gmail password, use App Password

AUTH_USER_MODEL = 'LaundryApp.UserProfile'
ROOT_URLCONF = 'LaundryConfig.urls'
LOGIN_REDIRECT_URL = '/redirect-after-login/'  # after login, always check role
LOGOUT_REDIRECT_URL = '/accounts/login/'

LOGIN_URL = 'login'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
             'builtins': [
                'django.contrib.humanize.templatetags.humanize',  # Add this
            ],
        },
    },
]

WSGI_APPLICATION = 'LaundryConfig.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL'),
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'


TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Configure static files for production
STATIC_URL = 'static/'

# Tell Django where to collect all static files for production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 

# Tell Django where to look for your static files during development
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Tell Whitenoise to compress your static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'LaundryApp': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

