# Generated by Django 5.2.5 on 2025-09-16 06:26

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KE', unique=True)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniquecode', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('payment_type', models.CharField(blank=True, choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other'), ('pending_payment', 'Pending Payment')], default='pending_payment', max_length=50)),
                ('payment_status', models.CharField(blank=True, choices=[('pending', 'pending'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('shop', models.CharField(choices=[('Shop A', 'Shop A'), ('Shop B', 'Shop B')], db_index=True, max_length=50)),
                ('delivery_date', models.DateField(db_index=True)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('Completed', 'Completed'), ('Delivered', 'Delivered')], db_index=True, default='pending', max_length=50)),
                ('addressdetails', models.TextField(blank=True, default='')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous_order_status', models.CharField(blank=True, max_length=50, null=True)),
                ('customer', models.ForeignKey(help_text='The customer associated with this order.', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='LaundryApp.customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicetype', models.CharField(choices=[('Washing', 'Washing'), ('Folding', 'Folding'), ('Ironing', 'Ironing'), ('Dry cleaning', 'Dry cleaning')], db_index=True, default='Washing', max_length=50)),
                ('itemtype', models.CharField(choices=[('Clothing', 'Clothing'), ('Bedding', 'Bedding'), ('Household items', 'Household items'), ('Footwares', 'Footwares')], default='Clothing', max_length=50)),
                ('itemname', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('itemcondition', models.CharField(choices=[('new', 'New'), ('Old', 'Old'), ('Torn', 'Torn')], default='new', help_text='Condition of the item.', max_length=50)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_item_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(help_text='The order this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='LaundryApp.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='LaundryApp.order')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(choices=[('Shop A', 'Shop A'), ('Shop B', 'Shop B')], default='None', max_length=50)),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
