# Generated by Django 5.2.5 on 2025-09-23 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenserecord',
            name='business',
        ),
        migrations.AlterUniqueTogether(
            name='expensefield',
            unique_together={('label',)},
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='LaundryApp.expensefield'),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='notes',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.RemoveField(
            model_name='expensefield',
            name='business',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
    ]
