# Generated by Django 5.2.5 on 2025-10-24 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='app_type',
        ),
        migrations.DeleteModel(
            name='LaundryProfile',
        ),
    ]
