# Generated by Django 5.2.5 on 2025-09-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Completed', 'Completed'), ('Delivered_picked', 'Delivered_picked')], db_index=True, default='pending', max_length=50),
        ),
    ]
