# Generated by Django 5.2.5 on 2025-09-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryApp', '0002_remove_expenserecord_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserecord',
            name='shop',
            field=models.CharField(choices=[('Shop A', 'Shop A'), ('Shop B', 'Shop B')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
