# Generated by Django 5.2.5 on 2025-10-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryApp', '0002_remove_userprofile_app_type_delete_laundryprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='shoptype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoptype', models.CharField(max_length=50)),
            ],
        ),
    ]
