# Generated by Django 5.2.5 on 2025-09-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryApp', '0002_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensefield',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
