# Generated by Django 5.2.5 on 2025-10-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryApp', '0003_shoptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoptype',
            name='shoptype',
            field=models.CharField(choices=[('Shop A', 'Shop A'), ('Shop B', 'Shop B'), ('Hotel', 'Hotel')], max_length=50),
        ),
    ]
