# Generated by Django 5.2.5 on 2025-09-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryApp', '0003_expenserecord_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('completed', 'cpompleted'), ('partial', 'partial')], db_index=True, default='pending', max_length=50),
        ),
    ]
