# Generated by Django 5.2.5 on 2025-09-22 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryApp', '0003_expensefield_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='expensefield',
            name='label',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='expensefield',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expense_fields', to='LaundryApp.business'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='expensefield',
            unique_together={('business', 'label')},
        ),
        migrations.RemoveField(
            model_name='expensefield',
            name='category',
        ),
    ]
