# Generated by Django 5.2.5 on 2025-09-09 09:15

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryApp', '0004_alter_order_order_status_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KE'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Completed', 'Completed'), ('Delivered', 'Delivered')], db_index=True, default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='shop',
            field=models.CharField(choices=[('Shop A', 'Shop A'), ('Shop B', 'Shop B')], default='None', max_length=50),
        ),
    ]
