# Generated by Django 5.2.5 on 2025-09-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryApp', '0004_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='servicetype',
            field=models.TextField(choices=[('Washing', 'Washing'), ('Folding', 'Folding'), ('Ironing', 'Ironing'), ('Dry cleaning', 'Dry cleaning')], db_index=True, default='Washing', max_length=50),
        ),
    ]
