# Generated by Django 5.2.5 on 2025-10-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryApp', '0004_alter_shoptype_shoptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uniquecode',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
    ]
