# Generated by Django 5.2.5 on 2025-09-22 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryApp', '0004_business_alter_expensefield_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserecord',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expense_records', to='LaundryApp.business'),
            preserve_default=False,
        ),
    ]
