# Generated by Django 5.2.5 on 2025-10-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryApp', '0005_alter_order_uniquecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.CharField(db_index=True, default=1, max_length=20),
            preserve_default=False,
        ),
    ]
