# Generated by Django 5.2.5 on 2025-09-29 03:23

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryApp', '0005_alter_orderitem_servicetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='servicetype',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Washing', 'Washing'), ('Folding', 'Folding'), ('Ironing', 'Ironing'), ('Dry cleaning', 'Dry cleaning')], db_index=True, default='Washing', max_length=50),
        ),
    ]
