# Generated by Django 5.2.5 on 2025-10-25 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryApp', '0006_order_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_by',
        ),
    ]
