# Generated by Django 5.2.5 on 2025-10-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryApp', '0006_alter_orderitem_servicetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('completed', 'complete'), ('partial', 'partial')], db_index=True, default='pending', max_length=50),
        ),
    ]
