# Generated by Django 5.2.5 on 2025-09-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryApp', '0006_alter_customer_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensefield',
            name='notes',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], db_index=True, default='pending_payment', max_length=50),
        ),
    ]
