# Generated by Django 5.2.5 on 2025-09-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryApp', '0007_expensefield_notes_alter_order_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensefield',
            name='notes',
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='notes',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
