# Generated by Django 5.2.5 on 2025-09-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryApp', '0008_remove_order_amount_paid_remove_order_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='balance',
        ),
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
