# Generated by Django 5.2.5 on 2025-09-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryApp', '0008_remove_expensefield_notes_expenserecord_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserecord',
            name='notes',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
