# Generated by Django 5.2.5 on 2025-10-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryApp', '0009_alter_order_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='itemcondition',
            field=models.CharField(choices=[('New', 'New'), ('Old', 'Old'), ('Torn', 'Torn')], db_index=True, default='new', max_length=50),
        ),
    ]
